### ISSUE TITLE
Potential confusion with sound scheme downloader

### ISSUE THREAD

**Issue by seediffusion** [ORelio/Sound-Manager#4]
Hi,
Let me start by saying just how much I love this program. I found out about it online a few days ago. It feels so good to once again have working startup/shutdown/logon/logoff sounds!

In the sound scheme downloader, when you select a sound scheme and download it, that scheme will remain selected for download when you launch the downloader again. This might be days, weeks or months later, and so the user might not know or remember that there's a scheme already selected, so they could end up downloading 2, 3 or 4 schemes at once when they only meant to download 1.
I'm using version 3.2.1 on Windows 10 build 22H2, 64-bit.

**Comment by ORelio** [comment]
Hi,

Thanks for your appreciation! At first I created this app simply to facilitate sharing sound schemes, but got quite frustrated when Microsoft started _removing_ sound events, so now SoundManager _also_ allows to restore the missing features. Glad you enjoy them :) Out of curiosity, did you find SoundManager through some google search?

Regarding Sound Scheme Downloader, the first time you launch it, you can check some boxes to select sound schemes, and it download them. In portable mode, it creates a Schemes folder next to SoundManager.exe, and in install mode it creates a SoundManager folder in My Music. The next time you launch it, schemes that are already on your computer are pre-checked. If you uncheck the box, it will delete the sound scheme from your computer. If the scheme is already on your computer, it will _not_ re-download it. Basically, it will make sure your folder matches your selection, so missing schemes in checklist are downloaded and unchecked schemes are deleted (but custom files in the Schemes folder that are unknown to the app are left as is). If this results in downloading exactly one scheme, it will offer to apply it.

Is there anything still unclear of that would need to be improved?

**Comment by seediffusion** [comment]
I found out about Sound Manager on [Mastodon](https://fedi.tips/what-is-mastodon-what-is-the-fediverse/).
What do you mean by portable mode? When I launched the executable initially, I didn't see anything about portable/installed modes. also, in the settings, there are options to reinstall and uninstall, so I assumed it had installed itself by adding values to the registry (not including sound schemes) and/or other folders.

**Comment by ORelio** [comment]
It's nice to hear that some people discover Sound Manager though word of mouth on social media 👍

If you go to the [releases](https://github.com/ORelio/Sound-Manager/releases) section, you'll see that each release is distributed either as "sound-manager.zip" or "sound-manager-setup.exe". If you use the Zip file, then you have a portable version. If you use the Setup file, then you have the installed version.

The portable version will store sound schemes in the app folder, while the installed version will store sound schemes in My Music.

As you pointed out, there are Uninstall/Reinstall buttons even in portable mode. The app needs to "install" itself in your user profile on first launch, which involves creating the sound scheme in Registry and creating a folder in AppData for storing sound files. See [How it works](https://github.com/ORelio/Sound-Manager?tab=readme-ov-file#how-it-works) for more details. So you can use "Uninstall" to remove all traces made in your user profile using the portable version (which includes disabling the "start with windows" setting and removing file associations, if enabled), and "Reinstall" to remove all traces then re-create the sound scheme. When using the Installed version, the "Uninstall" button will redirect to the uninstall program which performs the same Uninstall action but also removes SoundManager from the computer.

**Comment by ORelio** [comment]
I'm closing this issue as answered but feel free to reopen if needed.
Related: #5, https://github.com/ORelio/Sound-Manager-Schemes/pull/10
