### ISSUE TITLE
fix for the sound manager window for the background process and screen readers

### ISSUE THREAD

**Issue by aryanchoudharypro** [ORelio/Sound-Manager#7]
so, if we close a window, sometimes my screen reader goes to the sound manager windo. i know that we don't have to close it and so i don't, but some of my other friends don't and they press alt+f4 and close the window wich kills the proces. it would be good if this window could be hidden somehow, or could ignore the alt+f4 shortcut

**Comment by aryanchoudharypro** [comment]
seams github created 2 issues, sorry about that

**Comment by ORelio** [comment]
:arrow_forward: #8
